
function debut(){
var d = document.getElementById('debut')
    d.style.width = '390px'
    d.style.transition = '0.6s'
    var f = document.getElementById('fearless')
    f.style.width = '98px'
    f.style.transition = '0.6s'
    var s = document.getElementById('spn')
    s.style.width = '98px'
    s.style.transition = '0.6s'
    var r = document.getElementById('red')
    r.style.width = '98px'
    r.style.transition = '0.6s'
    var n = document.getElementById('nine')
    n.style.width = '98px'
    n.style.transition = '0.6s'
    var rp = document.getElementById('rep')
    rp.style.width = '98px'
    rp.style.transition = '0.6s'
    var l = document.getElementById('lover')
    l.style.width = '98px'
    l.style.transition = '0.6s'
    var fk = document.getElementById('folk')
    fk.style.width = '98px'
    fk.style.transition = '0.6s'
    var e = document.getElementById('ever')
    e.style.width = '98px'
    e.style.transition = '0.6s'
    var m = document.getElementById('mid')
    m.style.width = '98px'
    m.style.transition = '0.6s'
    var t = document.getElementById('ttpd')
    t.style.width = '98px'
    t.style.transition = '0.6s'
    var idebut = document.getElementById('idebut')
    idebut.style.transform = 'scale(1.1)'
    idebut.style.transition = '0.5s'
    var ifea = document.getElementById('ifea')
    ifea.style.transform = 'scale(1.0)'
    var ispn = document.getElementById('ispn')
    ispn.style.transform = 'scale(1.0)'
    var ired = document.getElementById('ired')
    ired.style.transform = 'scale(1.0)'
    var inine = document.getElementById('inine')
    inine.style.transform = 'scale(1.0)'
    var irep = document.getElementById('irep')
    irep.style.transform = 'scale(1.0)'
    var ilover = document.getElementById('ilover')
    ilover.style.transform = 'scale(1.0)'
    var ifolk = document.getElementById('ifolk')
    ifolk.style.transform = 'scale(1.0)'
    var iever = document.getElementById('iever')
    iever.style.transform = 'scale(1.0)'
    var imid = document.getElementById('imid')
    imid.style.transform = 'scale(1.0)'
    var ittpd = document.getElementById('ittpd')
    ittpd.style.transform = 'scale(1.0)'
}

 
function fearless(){
    var f = document.getElementById('fearless')
    f.style.width = '390px'
    f.style.transition = '0.6s'
    var d = document.getElementById('debut')
    d.style.width = '98px'
    d.style.transition = '0.6s'
    var s = document.getElementById('spn')
    s.style.width = '98px'
    s.style.transition = '0.6s'
    var r = document.getElementById('red')
    r.style.width = '98px'
    r.style.transition = '0.6s'
    var n = document.getElementById('nine')
    n.style.width = '98px'
    n.style.transition = '0.6s'
    var rp = document.getElementById('rep')
    rp.style.width = '98px'
    rp.style.transition = '0.6s'
    var l = document.getElementById('lover')
    l.style.width = '98px'
    l.style.transition = '0.6s'
    var fk = document.getElementById('folk')
    fk.style.width = '98px'
    fk.style.transition = '0.6s'
    var e = document.getElementById('ever')
    e.style.width = '98px'
    e.style.transition = '0.6s'
    var m = document.getElementById('mid')
    m.style.width = '98px'
    m.style.transition = '0.6s'
    var t = document.getElementById('ttpd')
    t.style.width = '98px'
    t.style.transition = '0.6s'
    var ifea = document.getElementById('ifea')
    ifea.style.transform = 'scale(1.1)'
    ifea.style.transition = '0.5s'
    var idebut = document.getElementById('idebut')
    idebut.style.transform = 'scale(1.0)'
    var ispn = document.getElementById('ispn')
    ispn.style.transform = 'scale(1.0)'
    var ired = document.getElementById('ired')
    ired.style.transform = 'scale(1.0)'
    var inine = document.getElementById('inine')
    inine.style.transform = 'scale(1.0)'
    var irep = document.getElementById('irep')
    irep.style.transform = 'scale(1.0)'
    var ilover = document.getElementById('ilover')
    ilover.style.transform = 'scale(1.0)'
    var ifolk = document.getElementById('ifolk')
    ifolk.style.transform = 'scale(1.0)'
    var iever = document.getElementById('iever')
    iever.style.transform = 'scale(1.0)'
    var imid = document.getElementById('imid')
    imid.style.transform = 'scale(1.0)'
    var ittpd = document.getElementById('ittpd')
    ittpd.style.transform = 'scale(1.0)'
}


function spn(){
    var s = document.getElementById('spn')
    s.style.width = '390px'
    s.style.transition = '0.6s'
    var f = document.getElementById('fearless')
    f.style.width = '98px'
    f.style.transition = '0.6s'
    var d = document.getElementById('debut')
    d.style.width = '98px'
    d.style.transition = '0.6s'
    var r = document.getElementById('red')
    r.style.width = '98px'
    r.style.transition = '0.6s'
    var n = document.getElementById('nine')
    n.style.width = '98px'
    n.style.transition = '0.6s'
    var rp = document.getElementById('rep')
    rp.style.width = '98px'
    rp.style.transition = '0.6s'
    var l = document.getElementById('lover')
    l.style.width = '98px'
    l.style.transition = '0.6s'
    var fk = document.getElementById('folk')
    fk.style.width = '98px'
    fk.style.transition = '0.6s'
    var e = document.getElementById('ever')
    e.style.width = '98px'
    e.style.transition = '0.6s'
    var m = document.getElementById('mid')
    m.style.width = '98px'
    m.style.transition = '0.6s'
    var t = document.getElementById('ttpd')
    t.style.width = '98px'
    t.style.transition = '0.6s'
    var ispn = document.getElementById('ispn')
    ispn.style.transform = 'scale(1.1)'
    ispn.style.transition = '0.5s'
    var idebut = document.getElementById('idebut')
    idebut.style.transform = 'scale(1.0)'
    var ispn = document.getElementById('ifea')
    ifea.style.transform = 'scale(1.0)'
    var ired = document.getElementById('ired')
    ired.style.transform = 'scale(1.0)'
    var inine = document.getElementById('inine')
    inine.style.transform = 'scale(1.0)'
    var irep = document.getElementById('irep')
    irep.style.transform = 'scale(1.0)'
    var ilover = document.getElementById('ilover')
    ilover.style.transform = 'scale(1.0)'
    var ifolk = document.getElementById('ifolk')
    ifolk.style.transform = 'scale(1.0)'
    var iever = document.getElementById('iever')
    iever.style.transform = 'scale(1.0)'
    var imid = document.getElementById('imid')
    imid.style.transform = 'scale(1.0)'
    var ittpd = document.getElementById('ittpd')
    ittpd.style.transform = 'scale(1.0)'
    
}

function red(){
    var r = document.getElementById('red')
    r.style.width = '390px'
    r.style.transition = '0.6s'
    var f = document.getElementById('fearless')
    f.style.width = '98px'
    f.style.transition = '0.6s'
    var s = document.getElementById('spn')
    s.style.width = '98px'
    s.style.transition = '0.6s'
    var d = document.getElementById('debut')
    d.style.width = '98px'
    d.style.transition = '0.6s'
    var n = document.getElementById('nine')
    n.style.width = '98px'
    n.style.transition = '0.6s'
    var rp = document.getElementById('rep')
    rp.style.width = '98px'
    rp.style.transition = '0.6s'
    var l = document.getElementById('lover')
    l.style.width = '98px'
    l.style.transition = '0.6s'
    var fk = document.getElementById('folk')
    fk.style.width = '98px'
    fk.style.transition = '0.6s'
    var e = document.getElementById('ever')
    e.style.width = '98px'
    e.style.transition = '0.6s'
    var m = document.getElementById('mid')
    m.style.width = '98px'
    m.style.transition = '0.6s'
    var t = document.getElementById('ttpd')
    t.style.width = '98px'
    t.style.transition = '0.6s'
    var ired= document.getElementById('ired')
    ired.style.transform = 'scale(1.1)'
    ired.style.transition = '0.5s'
    var idebut = document.getElementById('idebut')
    idebut.style.transform = 'scale(1.0)'
    var ispn = document.getElementById('ispn')
    ispn.style.transform = 'scale(1.0)'
    var ifea = document.getElementById('ifea')
    ifea.style.transform = 'scale(1.0)'
    var inine = document.getElementById('inine')
    inine.style.transform = 'scale(1.0)'
    var irep = document.getElementById('irep')
    irep.style.transform = 'scale(1.0)'
    var ilover = document.getElementById('ilover')
    ilover.style.transform = 'scale(1.0)'
    var ifolk = document.getElementById('ifolk')
    ifolk.style.transform = 'scale(1.0)'
    var iever = document.getElementById('iever')
    iever.style.transform = 'scale(1.0)'
    var imid = document.getElementById('imid')
    imid.style.transform = 'scale(1.0)'
    var ittpd = document.getElementById('ittpd')
    ittpd.style.transform = 'scale(1.0)'
}


function nine(){
    var n = document.getElementById('nine')
    n.style.width = '390px'
    n.style.transition = '0.6s'
    var f = document.getElementById('fearless')
    f.style.width = '98px'
    f.style.transition = '0.6s'
    var s = document.getElementById('spn')
    s.style.width = '98px'
    s.style.transition = '0.6s'
    var r = document.getElementById('red')
    r.style.width = '98px'
    r.style.transition = '0.6s'
    var d = document.getElementById('debut')
    d.style.width = '98px'
    d.style.transition = '0.6s'
    var rp = document.getElementById('rep')
    rp.style.width = '98px'
    rp.style.transition = '0.6s'
    var l = document.getElementById('lover')
    l.style.width = '98px'
    l.style.transition = '0.6s'
    var fk = document.getElementById('folk')
    fk.style.width = '98px'
    fk.style.transition = '0.6s'
    var e = document.getElementById('ever')
    e.style.width = '98px'
    e.style.transition = '0.6s'
    var m = document.getElementById('mid')
    m.style.width = '98px'
    m.style.transition = '0.6s'
    var t = document.getElementById('ttpd')
    t.style.width = '98px'
    t.style.transition = '0.6s'
    var inine = document.getElementById('inine')
    inine.style.transform = 'scale(1.1)'
    inine.style.transition = '0.5s'
    var idebut = document.getElementById('idebut')
    idebut.style.transform = 'scale(1.0)'
    var ispn = document.getElementById('ispn')
    ispn.style.transform = 'scale(1.0)'
    var ired = document.getElementById('ired')
    ired.style.transform = 'scale(1.0)'
    var ifea = document.getElementById('ifea')
    ifea.style.transform = 'scale(1.0)'
    var irep = document.getElementById('irep')
    irep.style.transform = 'scale(1.0)'
    var ilover = document.getElementById('ilover')
    ilover.style.transform = 'scale(1.0)'
    var ifolk = document.getElementById('ifolk')
    ifolk.style.transform = 'scale(1.0)'
    var iever = document.getElementById('iever')
    iever.style.transform = 'scale(1.0)'
    var imid = document.getElementById('imid')
    imid.style.transform = 'scale(1.0)'
    var ittpd = document.getElementById('ittpd')
    ittpd.style.transform = 'scale(1.0)'
}


function rep(){
    var rp = document.getElementById('rep')
    rp.style.width = '390px'
    rp.style.transition = '0.6s'
    var f = document.getElementById('fearless')
    f.style.width = '98px'
    f.style.transition = '0.6s'
    var s = document.getElementById('spn')
    s.style.width = '98px'
    s.style.transition = '0.6s'
    var r = document.getElementById('red')
    r.style.width = '98px'
    r.style.transition = '0.6s'
    var n = document.getElementById('nine')
    n.style.width = '98px'
    n.style.transition = '0.6s'
    var d = document.getElementById('debut')
    d.style.width = '98px'
    d.style.transition = '0.6s'
    var l = document.getElementById('lover')
    l.style.width = '98px'
    l.style.transition = '0.6s'
    var fk = document.getElementById('folk')
    fk.style.width = '98px'
    fk.style.transition = '0.6s'
    var e = document.getElementById('ever')
    e.style.width = '98px'
    e.style.transition = '0.6s'
    var m = document.getElementById('mid')
    m.style.width = '98px'
    m.style.transition = '0.6s'
    var t = document.getElementById('ttpd')
    t.style.width = '98px'
    t.style.transition = '0.6s'
    var irep = document.getElementById('irep')
    irep.style.transform = 'scale(1.1)'
    irep.style.transition = '0.5s'
    var idebut = document.getElementById('idebut')
    idebut.style.transform = 'scale(1.0)'
    var ispn = document.getElementById('ispn')
    ispn.style.transform = 'scale(1.0)'
    var ired = document.getElementById('ired')
    ired.style.transform = 'scale(1.0)'
    var inine = document.getElementById('inine')
    inine.style.transform = 'scale(1.0)'
    var ifea = document.getElementById('ifea')
    ifea.style.transform = 'scale(1.0)'
    var ilover = document.getElementById('ilover')
    ilover.style.transform = 'scale(1.0)'
    var ifolk = document.getElementById('ifolk')
    ifolk.style.transform = 'scale(1.0)'
    var iever = document.getElementById('iever')
    iever.style.transform = 'scale(1.0)'
    var imid = document.getElementById('imid')
    imid.style.transform = 'scale(1.0)'
    var ittpd = document.getElementById('ittpd')
    ittpd.style.transform = 'scale(1.0)'
}


function lover(){
    var l = document.getElementById('lover')
    l.style.width = '390px'
    l.style.transition = '0.6s'
    var f = document.getElementById('fearless')
    f.style.width = '98px'
    f.style.transition = '0.6s'
    var s = document.getElementById('spn')
    s.style.width = '98px'
    s.style.transition = '0.6s'
    var r = document.getElementById('red')
    r.style.width = '98px'
    r.style.transition = '0.6s'
    var n = document.getElementById('nine')
    n.style.width = '98px'
    n.style.transition = '0.6s'
    var rp = document.getElementById('rep')
    rp.style.width = '98px'
    rp.style.transition = '0.6s'
    var d = document.getElementById('debut')
    d.style.width = '98px'
    d.style.transition = '0.6s'
    var fk = document.getElementById('folk')
    fk.style.width = '98px'
    fk.style.transition = '0.6s'
    var e = document.getElementById('ever')
    e.style.width = '98px'
    e.style.transition = '0.6s'
    var m = document.getElementById('mid')
    m.style.width = '98px'
    m.style.transition = '0.6s'
    var t = document.getElementById('ttpd')
    t.style.width = '98px'
    t.style.transition = '0.6s'
    var ilover = document.getElementById('ilover')
    ilover.style.transform = 'scale(1.1)'
    ilover.style.transition = '0.5s'
    var idebut = document.getElementById('idebut')
    idebut.style.transform = 'scale(1.0)'
    var ispn = document.getElementById('ispn')
    ispn.style.transform = 'scale(1.0)'
    var ired = document.getElementById('ired')
    ired.style.transform = 'scale(1.0)'
    var inine = document.getElementById('inine')
    inine.style.transform = 'scale(1.0)'
    var irep = document.getElementById('irep')
    irep.style.transform = 'scale(1.0)'
    var ifea = document.getElementById('ifea')
    ifea.style.transform = 'scale(1.0)'
    var ifolk = document.getElementById('ifolk')
    ifolk.style.transform = 'scale(1.0)'
    var iever = document.getElementById('iever')
    iever.style.transform = 'scale(1.0)'
    var imid = document.getElementById('imid')
    imid.style.transform = 'scale(1.0)'
    var ittpd = document.getElementById('ittpd')
    ittpd.style.transform = 'scale(1.0)'
}


function folk(){
    var fk = document.getElementById('folk')
    fk.style.width = '390px'
    fk.style.transition = '0.6s'
    var f = document.getElementById('fearless')
    f.style.width = '98px'
    f.style.transition = '0.6s'
    var s = document.getElementById('spn')
    s.style.width = '98px'
    s.style.transition = '0.6s'
    var r = document.getElementById('red')
    r.style.width = '98px'
    r.style.transition = '0.6s'
    var n = document.getElementById('nine')
    n.style.width = '98px'
    n.style.transition = '0.6s'
    var rp = document.getElementById('rep')
    rp.style.width = '98px'
    rp.style.transition = '0.6s'
    var l = document.getElementById('lover')
    l.style.width = '98px'
    l.style.transition = '0.6s'
    var d = document.getElementById('debut')
    d.style.width = '98px'
    d.style.transition = '0.6s'
    var e = document.getElementById('ever')
    e.style.width = '98px'
    e.style.transition = '0.6s'
    var m = document.getElementById('mid')
    m.style.width = '98px'
    m.style.transition = '0.6s'
    var t = document.getElementById('ttpd')
    t.style.width = '98px'
    t.style.transition = '0.6s'
    var ifolk = document.getElementById('ifolk')
    ifolk.style.transform = 'scale(1.1)'
    ifolk.style.transition = '0.5s'
    var idebut = document.getElementById('idebut')
    idebut.style.transform = 'scale(1.0)'
    var ispn = document.getElementById('ispn')
    ispn.style.transform = 'scale(1.0)'
    var ired = document.getElementById('ired')
    ired.style.transform = 'scale(1.0)'
    var inine = document.getElementById('inine')
    inine.style.transform = 'scale(1.0)'
    var irep = document.getElementById('irep')
    irep.style.transform = 'scale(1.0)'
    var ilover = document.getElementById('ilover')
    ilover.style.transform = 'scale(1.0)'
    var ifea = document.getElementById('ifea')
    ifea.style.transform = 'scale(1.0)'
    var iever = document.getElementById('iever')
    iever.style.transform = 'scale(1.0)'
    var imid = document.getElementById('imid')
    imid.style.transform = 'scale(1.0)'
    var ittpd = document.getElementById('ittpd')
    ittpd.style.transform = 'scale(1.0)'
}

function ever(){
    var e = document.getElementById('ever')
    e.style.width = '390px'
    e.style.transition = '0.6s'
    var f = document.getElementById('fearless')
    f.style.width = '98px'
    f.style.transition = '0.6s'
    var s = document.getElementById('spn')
    s.style.width = '98px'
    s.style.transition = '0.6s'
    var r = document.getElementById('red')
    r.style.width = '98px'
    r.style.transition = '0.6s'
    var n = document.getElementById('nine')
    n.style.width = '98px'
    n.style.transition = '0.6s'
    var rp = document.getElementById('rep')
    rp.style.width = '98px'
    rp.style.transition = '0.6s'
    var l = document.getElementById('lover')
    l.style.width = '98px'
    l.style.transition = '0.6s'
    var fk = document.getElementById('folk')
    fk.style.width = '98px'
    fk.style.transition = '0.6s'
    var d = document.getElementById('debut')
    d.style.width = '98px'
    d.style.transition = '0.6s'
    var m = document.getElementById('mid')
    m.style.width = '98px'
    m.style.transition = '0.6s'
    var t = document.getElementById('ttpd')
    t.style.width = '98px'
    t.style.transition = '0.6s'
    var iever = document.getElementById('iever')
    iever.style.transform = 'scale(1.1)'
    iever.style.transition = '0.5s'
    var idebut = document.getElementById('idebut')
    idebut.style.transform = 'scale(1.0)'
    var ispn = document.getElementById('ispn')
    ispn.style.transform = 'scale(1.0)'
    var ired = document.getElementById('ired')
    ired.style.transform = 'scale(1.0)'
    var inine = document.getElementById('inine')
    inine.style.transform = 'scale(1.0)'
    var irep = document.getElementById('irep')
    irep.style.transform = 'scale(1.0)'
    var ilover = document.getElementById('ilover')
    ilover.style.transform = 'scale(1.0)'
    var ifolk = document.getElementById('ifolk')
    ifolk.style.transform = 'scale(1.0)'
    var ifea = document.getElementById('ifea')
    ifea.style.transform = 'scale(1.0)'
    var imid = document.getElementById('imid')
    imid.style.transform = 'scale(1.0)'
    var ittpd = document.getElementById('ittpd')
    ittpd.style.transform = 'scale(1.0)'
}

function mid(){
    var m = document.getElementById('mid')
    m.style.width = '390px'
    m.style.transition = '0.6s'
    var f = document.getElementById('fearless')
    f.style.width = '98px'
    f.style.transition = '0.6s'
    var s = document.getElementById('spn')
    s.style.width = '98px'
    s.style.transition = '0.6s'
    var r = document.getElementById('red')
    r.style.width = '98px'
    r.style.transition = '0.6s'
    var n = document.getElementById('nine')
    n.style.width = '98px'
    n.style.transition = '0.6s'
    var rp = document.getElementById('rep')
    rp.style.width = '98px'
    rp.style.transition = '0.6s'
    var l = document.getElementById('lover')
    l.style.width = '98px'
    l.style.transition = '0.6s'
    var fk = document.getElementById('folk')
    fk.style.width = '98px'
    fk.style.transition = '0.6s'
    var e = document.getElementById('ever')
    e.style.width = '98px'
    e.style.transition = '0.6s'
    var d = document.getElementById('debut')
    d.style.width = '98px'
    d.style.transition = '0.6s'
    var t = document.getElementById('ttpd')
    t.style.width = '98px'
    t.style.transition = '0.6s'
    var imid = document.getElementById('imid')
    imid.style.transform = 'scale(1.1)'
    imid.style.transition = '0.5s'
    var idebut = document.getElementById('idebut')
    idebut.style.transform = 'scale(1.0)'
    var ispn = document.getElementById('ispn')
    ispn.style.transform = 'scale(1.0)'
    var ired = document.getElementById('ired')
    ired.style.transform = 'scale(1.0)'
    var inine = document.getElementById('inine')
    inine.style.transform = 'scale(1.0)'
    var irep = document.getElementById('irep')
    irep.style.transform = 'scale(1.0)'
    var ilover = document.getElementById('ilover')
    ilover.style.transform = 'scale(1.0)'
    var ifolk = document.getElementById('ifolk')
    ifolk.style.transform = 'scale(1.0)'
    var iever = document.getElementById('iever')
    iever.style.transform = 'scale(1.0)'
    var ifea = document.getElementById('ifea')
    ifea.style.transform = 'scale(1.0)'
    var ittpd = document.getElementById('ittpd')
    ittpd.style.transform = 'scale(1.0)'
}

function ttpd(){
    var t = document.getElementById('ttpd')
    t.style.width = '390px'
    t.style.transition = '0.6s'
    var f = document.getElementById('fearless')
    f.style.width = '98px'
    f.style.transition = '0.6s'
    var s = document.getElementById('spn')
    s.style.width = '98px'
    s.style.transition = '0.6s'
    var r = document.getElementById('red')
    r.style.width = '98px'
    r.style.transition = '0.6s'
    var n = document.getElementById('nine')
    n.style.width = '98px'
    n.style.transition = '0.6s'
    var rp = document.getElementById('rep')
    rp.style.width = '98px'
    rp.style.transition = '0.6s'
    var l = document.getElementById('lover')
    l.style.width = '98px'
    l.style.transition = '0.6s'
    var fk = document.getElementById('folk')
    fk.style.width = '98px'
    fk.style.transition = '0.6s'
    var e = document.getElementById('ever')
    e.style.width = '98px'
    e.style.transition = '0.6s'
    var m = document.getElementById('mid')
    m.style.width = '98px'
    m.style.transition = '0.6s'
    var d = document.getElementById('debut')
    d.style.width = '98px'
    d.style.transition = '0.6s'
    var ittpd = document.getElementById('ittpd')
    ittpd.style.transform = 'scale(1.1)'
    ittpd.style.transition = '0.5s'
    var idebut = document.getElementById('idebut')
    idebut.style.transform = 'scale(1.0)'
    var ispn = document.getElementById('ispn')
    ispn.style.transform = 'scale(1.0)'
    var ired = document.getElementById('ired')
    ired.style.transform = 'scale(1.0)'
    var inine = document.getElementById('inine')
    inine.style.transform = 'scale(1.0)'
    var irep = document.getElementById('irep')
    irep.style.transform = 'scale(1.0)'
    var ilover = document.getElementById('ilover')
    ilover.style.transform = 'scale(1.0)'
    var ifolk = document.getElementById('ifolk')
    ifolk.style.transform = 'scale(1.0)'
    var iever = document.getElementById('iever')
    iever.style.transform = 'scale(1.0)'
    var imid = document.getElementById('imid')
    imid.style.transform = 'scale(1.0)'
    var ifea = document.getElementById('ifea')
    ifea.style.transform = 'scale(1.0)'
}