
var art = document.getElementById('art')

function debut(){

    art.style.marginLeft = '1.5%'
    art.style.transition = '0.6s'

var music = document.getElementById('music')
    music.style.background = '#a5c9a5'
    music.style.transition = '0.6s'

var d = document.getElementById('debut')
    d.style.width = '30%'
    d.style.transition = '0.6s'
    var f = document.getElementById('fearless')
    f.style.width = '7%'
    f.style.transition = '0.6s'
    var s = document.getElementById('spn')
    s.style.width = '7%'
    s.style.transition = '0.6s'
    var r = document.getElementById('red')
    r.style.width = '7%'
    r.style.transition = '0.6s'
    var n = document.getElementById('nine')
    n.style.width = '7%'
    n.style.transition = '0.6s'
    var rp = document.getElementById('rep')
    rp.style.width = '7%'
    rp.style.transition = '0.6s'
    var l = document.getElementById('lover')
    l.style.width = '7%'
    l.style.transition = '0.6s'
    var fk = document.getElementById('folk')
    fk.style.width = '7%'
    fk.style.transition = '0.6s'
    var e = document.getElementById('ever')
    e.style.width = '7%'
    e.style.transition = '0.6s'
    var m = document.getElementById('mid')
    m.style.width = '7%'
    m.style.transition = '0.6s'
    var t = document.getElementById('ttpd')
    t.style.width = '7%'
    t.style.transition = '0.6s'
    var idebut = document.getElementById('idebut')
    idebut.style.transform = 'scale(1.1)'
    idebut.style.transition = '0.5s'
    var ifea = document.getElementById('ifea')
    ifea.style.transform = 'scale(1.0)'
    var ispn = document.getElementById('ispn')
    ispn.style.transform = 'scale(1.0)'
    var ired = document.getElementById('ired')
    ired.style.transform = 'scale(1.0)'
    var inine = document.getElementById('inine')
    inine.style.transform = 'scale(1.0)'
    var irep = document.getElementById('irep')
    irep.style.transform = 'scale(1.0)'
    var ilover = document.getElementById('ilover')
    ilover.style.transform = 'scale(1.0)'
    var ifolk = document.getElementById('ifolk')
    ifolk.style.transform = 'scale(1.0)'
    var iever = document.getElementById('iever')
    iever.style.transform = 'scale(1.0)'
    var imid = document.getElementById('imid')
    imid.style.transform = 'scale(1.0)'
    var ittpd = document.getElementById('ittpd')
    ittpd.style.transform = 'scale(1.0)'
}

 
function fearless(){
    var f = document.getElementById('fearless')
    f.style.width = '400px'
    f.style.transition = '0.6s'

    art.style.marginLeft = '8px'
    art.style.transition = '0.6s'

var music = document.getElementById('music')
    music.style.background = '#efc180'
    music.style.transition = '0.6s'

    var d = document.getElementById('debut')
    d.style.width = '95.4px'
    d.style.transition = '0.6s'
    var s = document.getElementById('spn')
    s.style.width = '95.4px'
    s.style.transition = '0.6s'
    var r = document.getElementById('red')
    r.style.width = '95.4px'
    r.style.transition = '0.6s'
    var n = document.getElementById('nine')
    n.style.width = '95.4px'
    n.style.transition = '0.6s'
    var rp = document.getElementById('rep')
    rp.style.width = '95.4px'
    rp.style.transition = '0.6s'
    var l = document.getElementById('lover')
    l.style.width = '95.4px'
    l.style.transition = '0.6s'
    var fk = document.getElementById('folk')
    fk.style.width = '95.4px'
    fk.style.transition = '0.6s'
    var e = document.getElementById('ever')
    e.style.width = '95.4px'
    e.style.transition = '0.6s'
    var m = document.getElementById('mid')
    m.style.width = '95.4px'
    m.style.transition = '0.6s'
    var t = document.getElementById('ttpd')
    t.style.width = '95.4px'
    t.style.transition = '0.6s'
    var ifea = document.getElementById('ifea')
    ifea.style.transform = 'scale(1.1)'
    ifea.style.transition = '0.5s'
    var idebut = document.getElementById('idebut')
    idebut.style.transform = 'scale(1.0)'
    var ispn = document.getElementById('ispn')
    ispn.style.transform = 'scale(1.0)'
    var ired = document.getElementById('ired')
    ired.style.transform = 'scale(1.0)'
    var inine = document.getElementById('inine')
    inine.style.transform = 'scale(1.0)'
    var irep = document.getElementById('irep')
    irep.style.transform = 'scale(1.0)'
    var ilover = document.getElementById('ilover')
    ilover.style.transform = 'scale(1.0)'
    var ifolk = document.getElementById('ifolk')
    ifolk.style.transform = 'scale(1.0)'
    var iever = document.getElementById('iever')
    iever.style.transform = 'scale(1.0)'
    var imid = document.getElementById('imid')
    imid.style.transform = 'scale(1.0)'
    var ittpd = document.getElementById('ittpd')
    ittpd.style.transform = 'scale(1.0)'
}


function spn(){
    var s = document.getElementById('spn')
    s.style.width = '400px'
    s.style.transition = '0.6s'
    art.style.marginLeft = '8px'
    art.style.transition = '0.6s'

    var music = document.getElementById('music')
    music.style.background = '#c7a8cd'
    music.style.transition = '0.6s'

    var f = document.getElementById('fearless')
    f.style.width = '95.4px'
    f.style.transition = '0.6s'
    var d = document.getElementById('debut')
    d.style.width = '95.4px'
    d.style.transition = '0.6s'
    var r = document.getElementById('red')
    r.style.width = '95.4px'
    r.style.transition = '0.6s'
    var n = document.getElementById('nine')
    n.style.width = '95.4px'
    n.style.transition = '0.6s'
    var rp = document.getElementById('rep')
    rp.style.width = '95.4px'
    rp.style.transition = '0.6s'
    var l = document.getElementById('lover')
    l.style.width = '95.4px'
    l.style.transition = '0.6s'
    var fk = document.getElementById('folk')
    fk.style.width = '95.4px'
    fk.style.transition = '0.6s'
    var e = document.getElementById('ever')
    e.style.width = '95.4px'
    e.style.transition = '0.6s'
    var m = document.getElementById('mid')
    m.style.width = '95.4px'
    m.style.transition = '0.6s'
    var t = document.getElementById('ttpd')
    t.style.width = '95.4px'
    t.style.transition = '0.6s'
    var ispn = document.getElementById('ispn')
    ispn.style.transform = 'scale(1.1)'
    ispn.style.transition = '0.5s'
    var idebut = document.getElementById('idebut')
    idebut.style.transform = 'scale(1.0)'
    var ispn = document.getElementById('ifea')
    ifea.style.transform = 'scale(1.0)'
    var ired = document.getElementById('ired')
    ired.style.transform = 'scale(1.0)'
    var inine = document.getElementById('inine')
    inine.style.transform = 'scale(1.0)'
    var irep = document.getElementById('irep')
    irep.style.transform = 'scale(1.0)'
    var ilover = document.getElementById('ilover')
    ilover.style.transform = 'scale(1.0)'
    var ifolk = document.getElementById('ifolk')
    ifolk.style.transform = 'scale(1.0)'
    var iever = document.getElementById('iever')
    iever.style.transform = 'scale(1.0)'
    var imid = document.getElementById('imid')
    imid.style.transform = 'scale(1.0)'
    var ittpd = document.getElementById('ittpd')
    ittpd.style.transform = 'scale(1.0)'
    
}

function red(){
    var r = document.getElementById('red')
    r.style.width = '400px'
    r.style.transition = '0.6s'
    art.style.marginLeft = '8px'
    art.style.transition = '0.6s'

    var music = document.getElementById('music')
    music.style.background = '#7a2e39'
    music.style.transition = '0.6s'

    var f = document.getElementById('fearless')
    f.style.width = '95.4px'
    f.style.transition = '0.6s'
    var s = document.getElementById('spn')
    s.style.width = '95.4px'
    s.style.transition = '0.6s'
    var d = document.getElementById('debut')
    d.style.width = '95.4px'
    d.style.transition = '0.6s'
    var n = document.getElementById('nine')
    n.style.width = '95.4px'
    n.style.transition = '0.6s'
    var rp = document.getElementById('rep')
    rp.style.width = '95.4px'
    rp.style.transition = '0.6s'
    var l = document.getElementById('lover')
    l.style.width = '95.4px'
    l.style.transition = '0.6s'
    var fk = document.getElementById('folk')
    fk.style.width = '95.4px'
    fk.style.transition = '0.6s'
    var e = document.getElementById('ever')
    e.style.width = '95.4px'
    e.style.transition = '0.6s'
    var m = document.getElementById('mid')
    m.style.width = '95.4px'
    m.style.transition = '0.6s'
    var t = document.getElementById('ttpd')
    t.style.width = '95.4px'
    t.style.transition = '0.8s'
    var ired= document.getElementById('ired')
    ired.style.transform = 'scale(1.1)'
    ired.style.transition = '0.8s'
    var idebut = document.getElementById('idebut')
    idebut.style.transform = 'scale(1.0)'
    var ispn = document.getElementById('ispn')
    ispn.style.transform = 'scale(1.0)'
    var ifea = document.getElementById('ifea')
    ifea.style.transform = 'scale(1.0)'
    var inine = document.getElementById('inine')
    inine.style.transform = 'scale(1.0)'
    var irep = document.getElementById('irep')
    irep.style.transform = 'scale(1.0)'
    var ilover = document.getElementById('ilover')
    ilover.style.transform = 'scale(1.0)'
    var ifolk = document.getElementById('ifolk')
    ifolk.style.transform = 'scale(1.0)'
    var iever = document.getElementById('iever')
    iever.style.transform = 'scale(1.0)'
    var imid = document.getElementById('imid')
    imid.style.transform = 'scale(1.0)'
    var ittpd = document.getElementById('ittpd')
    ittpd.style.transform = 'scale(1.0)'
}


function nine(){
    var n = document.getElementById('nine')
    n.style.width = '400px'
    n.style.transition = '0.8s'
    art.style.marginLeft = '8px'
    art.style.transition = '0.8s'

    var music = document.getElementById('music')
    music.style.background = '#b5e5f8'
    music.style.transition = '0.8s'

    var f = document.getElementById('fearless')
    f.style.width = '95.4px'
    f.style.transition = '0.8s'
    var s = document.getElementById('spn')
    s.style.width = '95.4px'
    s.style.transition = '0.8s'
    var r = document.getElementById('red')
    r.style.width = '95.4px'
    r.style.transition = '0.8s'
    var d = document.getElementById('debut')
    d.style.width = '95.4px'
    d.style.transition = '0.8s'
    var rp = document.getElementById('rep')
    rp.style.width = '95.4px'
    rp.style.transition = '0.8s'
    var l = document.getElementById('lover')
    l.style.width = '95.4px'
    l.style.transition = '0.8s'
    var fk = document.getElementById('folk')
    fk.style.width = '95.4px'
    fk.style.transition = '0.8s'
    var e = document.getElementById('ever')
    e.style.width = '95.4px'
    e.style.transition = '0.8s'
    var m = document.getElementById('mid')
    m.style.width = '95.4px'
    m.style.transition = '0.8s'
    var t = document.getElementById('ttpd')
    t.style.width = '95.4px'
    t.style.transition = '0.8s'
    var inine = document.getElementById('inine')
    inine.style.transform = 'scale(1.1)'
    inine.style.transition = '0.8s'
    var idebut = document.getElementById('idebut')
    idebut.style.transform = 'scale(1.0)'
    var ispn = document.getElementById('ispn')
    ispn.style.transform = 'scale(1.0)'
    var ired = document.getElementById('ired')
    ired.style.transform = 'scale(1.0)'
    var ifea = document.getElementById('ifea')
    ifea.style.transform = 'scale(1.0)'
    var irep = document.getElementById('irep')
    irep.style.transform = 'scale(1.0)'
    var ilover = document.getElementById('ilover')
    ilover.style.transform = 'scale(1.0)'
    var ifolk = document.getElementById('ifolk')
    ifolk.style.transform = 'scale(1.0)'
    var iever = document.getElementById('iever')
    iever.style.transform = 'scale(1.0)'
    var imid = document.getElementById('imid')
    imid.style.transform = 'scale(1.0)'
    var ittpd = document.getElementById('ittpd')
    ittpd.style.transform = 'scale(1.0)'
}


function rep(){
    var rp = document.getElementById('rep')
    rp.style.width = '400px'
    rp.style.transition = '0.8s'
    art.style.marginLeft = '8px'
    art.style.transition = '0.8s'

    var music = document.getElementById('music')
    music.style.background = '#424242'
    music.style.transition = '0.8s'

    var f = document.getElementById('fearless')
    f.style.width = '95.4px'
    f.style.transition = '0.8s'
    var s = document.getElementById('spn')
    s.style.width = '95.4px'
    s.style.transition = '0.8s'
    var r = document.getElementById('red')
    r.style.width = '95.4px'
    r.style.transition = '0.8s'
    var n = document.getElementById('nine')
    n.style.width = '95.4px'
    n.style.transition = '0.8s'
    var d = document.getElementById('debut')
    d.style.width = '95.4px'
    d.style.transition = '0.8s'
    var l = document.getElementById('lover')
    l.style.width = '95.4px'
    l.style.transition = '0.8s'
    var fk = document.getElementById('folk')
    fk.style.width = '95.4px'
    fk.style.transition = '0.8s'
    var e = document.getElementById('ever')
    e.style.width = '95.4px'
    e.style.transition = '0.8s'
    var m = document.getElementById('mid')
    m.style.width = '95.4px'
    m.style.transition = '0.8s'
    var t = document.getElementById('ttpd')
    t.style.width = '95.4px'
    t.style.transition = '0.8s'
    var irep = document.getElementById('irep')
    irep.style.transform = 'scale(1.1)'
    irep.style.transition = '0.8s'
    var idebut = document.getElementById('idebut')
    idebut.style.transform = 'scale(1.0)'
    var ispn = document.getElementById('ispn')
    ispn.style.transform = 'scale(1.0)'
    var ired = document.getElementById('ired')
    ired.style.transform = 'scale(1.0)'
    var inine = document.getElementById('inine')
    inine.style.transform = 'scale(1.0)'
    var ifea = document.getElementById('ifea')
    ifea.style.transform = 'scale(1.0)'
    var ilover = document.getElementById('ilover')
    ilover.style.transform = 'scale(1.0)'
    var ifolk = document.getElementById('ifolk')
    ifolk.style.transform = 'scale(1.0)'
    var iever = document.getElementById('iever')
    iever.style.transform = 'scale(1.0)'
    var imid = document.getElementById('imid')
    imid.style.transform = 'scale(1.0)'
    var ittpd = document.getElementById('ittpd')
    ittpd.style.transform = 'scale(1.0)'
}


function lover(){
    var l = document.getElementById('lover')
    l.style.width = '400px'
    l.style.transition = '0.8s'
    art.style.marginLeft = '8px'
    art.style.transition = '0.8s'

    var music = document.getElementById('music')
    music.style.background = '#f7b0cc'
    music.style.transition = '0.8s'

    var f = document.getElementById('fearless')
    f.style.width = '95.4px'
    f.style.transition = '0.8s'
    var s = document.getElementById('spn')
    s.style.width = '95.4px'
    s.style.transition = '0.8s'
    var r = document.getElementById('red')
    r.style.width = '95.4px'
    r.style.transition = '0.8s'
    var n = document.getElementById('nine')
    n.style.width = '95.4px'
    n.style.transition = '0.8s'
    var rp = document.getElementById('rep')
    rp.style.width = '95.4px'
    rp.style.transition = '0.8s'
    var d = document.getElementById('debut')
    d.style.width = '95.4px'
    d.style.transition = '0.8s'
    var fk = document.getElementById('folk')
    fk.style.width = '95.4px'
    fk.style.transition = '0.8s'
    var e = document.getElementById('ever')
    e.style.width = '95.4px'
    e.style.transition = '0.8s'
    var m = document.getElementById('mid')
    m.style.width = '95.4px'
    m.style.transition = '0.8s'
    var t = document.getElementById('ttpd')
    t.style.width = '95.4px'
    t.style.transition = '0.8s'
    var ilover = document.getElementById('ilover')
    ilover.style.transform = 'scale(1.1)'
    ilover.style.transition = '0.8s'
    var idebut = document.getElementById('idebut')
    idebut.style.transform = 'scale(1.0)'
    var ispn = document.getElementById('ispn')
    ispn.style.transform = 'scale(1.0)'
    var ired = document.getElementById('ired')
    ired.style.transform = 'scale(1.0)'
    var inine = document.getElementById('inine')
    inine.style.transform = 'scale(1.0)'
    var irep = document.getElementById('irep')
    irep.style.transform = 'scale(1.0)'
    var ifea = document.getElementById('ifea')
    ifea.style.transform = 'scale(1.0)'
    var ifolk = document.getElementById('ifolk')
    ifolk.style.transform = 'scale(1.0)'
    var iever = document.getElementById('iever')
    iever.style.transform = 'scale(1.0)'
    var imid = document.getElementById('imid')
    imid.style.transform = 'scale(1.0)'
    var ittpd = document.getElementById('ittpd')
    ittpd.style.transform = 'scale(1.0)'
}


function folk(){
    var fk = document.getElementById('folk')
    fk.style.width = '400px'
    fk.style.transition = '0.8s'
    art.style.marginLeft = '8px'
    art.style.transition = '0.8s'

    var music = document.getElementById('music')
    music.style.background = '#979797'
    music.style.transition = '0.8s'

    var f = document.getElementById('fearless')
    f.style.width = '95.4px'
    f.style.transition = '0.8s'
    var s = document.getElementById('spn')
    s.style.width = '95.4px'
    s.style.transition = '0.8s'
    var r = document.getElementById('red')
    r.style.width = '95.4px'
    r.style.transition = '0.8s'
    var n = document.getElementById('nine')
    n.style.width = '95.4px'
    n.style.transition = '0.8s'
    var rp = document.getElementById('rep')
    rp.style.width = '95.4px'
    rp.style.transition = '0.8s'
    var l = document.getElementById('lover')
    l.style.width = '95.4px'
    l.style.transition = '0.8s'
    var d = document.getElementById('debut')
    d.style.width = '95.4px'
    d.style.transition = '0.8s'
    var e = document.getElementById('ever')
    e.style.width = '95.4px'
    e.style.transition = '0.8s'
    var m = document.getElementById('mid')
    m.style.width = '95.4px'
    m.style.transition = '0.8s'
    var t = document.getElementById('ttpd')
    t.style.width = '95.4px'
    t.style.transition = '0.8s'
    var ifolk = document.getElementById('ifolk')
    ifolk.style.transform = 'scale(1.1)'
    ifolk.style.transition = '0.5s'
    var idebut = document.getElementById('idebut')
    idebut.style.transform = 'scale(1.0)'
    var ispn = document.getElementById('ispn')
    ispn.style.transform = 'scale(1.0)'
    var ired = document.getElementById('ired')
    ired.style.transform = 'scale(1.0)'
    var inine = document.getElementById('inine')
    inine.style.transform = 'scale(1.0)'
    var irep = document.getElementById('irep')
    irep.style.transform = 'scale(1.0)'
    var ilover = document.getElementById('ilover')
    ilover.style.transform = 'scale(1.0)'
    var ifea = document.getElementById('ifea')
    ifea.style.transform = 'scale(1.0)'
    var iever = document.getElementById('iever')
    iever.style.transform = 'scale(1.0)'
    var imid = document.getElementById('imid')
    imid.style.transform = 'scale(1.0)'
    var ittpd = document.getElementById('ittpd')
    ittpd.style.transform = 'scale(1.0)'
}

function ever(){
    var e = document.getElementById('ever')
    e.style.width = '400px'
    e.style.transition = '0.8s'
    art.style.marginLeft = '8px'
    art.style.transition = '0.8s'

    var music = document.getElementById('music')
    music.style.background = '#c5ac90'
    music.style.transition = '0.8s'

    var f = document.getElementById('fearless')
    f.style.width = '95.4px'
    f.style.transition = '0.8s'
    var s = document.getElementById('spn')
    s.style.width = '95.4px'
    s.style.transition = '0.8s'
    var r = document.getElementById('red')
    r.style.width = '95.4px'
    r.style.transition = '0.8s'
    var n = document.getElementById('nine')
    n.style.width = '95.4px'
    n.style.transition = '0.8s'
    var rp = document.getElementById('rep')
    rp.style.width = '95.4px'
    rp.style.transition = '0.8s'
    var l = document.getElementById('lover')
    l.style.width = '95.4px'
    l.style.transition = '0.8s'
    var fk = document.getElementById('folk')
    fk.style.width = '95.4px'
    fk.style.transition = '0.8s'
    var d = document.getElementById('debut')
    d.style.width = '95.4px'
    d.style.transition = '0.8s'
    var m = document.getElementById('mid')
    m.style.width = '95.4px'
    m.style.transition = '0.8s'
    var t = document.getElementById('ttpd')
    t.style.width = '95.4px'
    t.style.transition = '0.8s'
    var iever = document.getElementById('iever')
    iever.style.transform = 'scale(1.1)'
    iever.style.transition = '0.8s'
    var idebut = document.getElementById('idebut')
    idebut.style.transform = 'scale(1.0)'
    var ispn = document.getElementById('ispn')
    ispn.style.transform = 'scale(1.0)'
    var ired = document.getElementById('ired')
    ired.style.transform = 'scale(1.0)'
    var inine = document.getElementById('inine')
    inine.style.transform = 'scale(1.0)'
    var irep = document.getElementById('irep')
    irep.style.transform = 'scale(1.0)'
    var ilover = document.getElementById('ilover')
    ilover.style.transform = 'scale(1.0)'
    var ifolk = document.getElementById('ifolk')
    ifolk.style.transform = 'scale(1.0)'
    var ifea = document.getElementById('ifea')
    ifea.style.transform = 'scale(1.0)'
    var imid = document.getElementById('imid')
    imid.style.transform = 'scale(1.0)'
    var ittpd = document.getElementById('ittpd')
    ittpd.style.transform = 'scale(1.0)'
}

function mid(){
    var m = document.getElementById('mid')
    m.style.width = '400px'
    m.style.transition = '0.8s'
    art.style.marginLeft = '8px'
    art.style.transition = '0.8s'

    var music = document.getElementById('music')
    music.style.background = '#242e47'
    music.style.transition = '0.8s'

    var f = document.getElementById('fearless')
    f.style.width = '95.4px'
    f.style.transition = '0.8s'
    var s = document.getElementById('spn')
    s.style.width = '95.4px'
    s.style.transition = '0.8s'
    var r = document.getElementById('red')
    r.style.width = '95.4px'
    r.style.transition = '0.6s'
    var n = document.getElementById('nine')
    n.style.width = '95.4px'
    n.style.transition = '0.8s'
    var rp = document.getElementById('rep')
    rp.style.width = '95.4px'
    rp.style.transition = '0.8s'
    var l = document.getElementById('lover')
    l.style.width = '95.4px'
    l.style.transition = '0.8s'
    var fk = document.getElementById('folk')
    fk.style.width = '95.4px'
    fk.style.transition = '0.8s'
    var e = document.getElementById('ever')
    e.style.width = '95.4px'
    e.style.transition = '0.8s'
    var d = document.getElementById('debut')
    d.style.width = '95.4px'
    d.style.transition = '0.8s'
    var t = document.getElementById('ttpd')
    t.style.width = '95.4px'
    t.style.transition = '0.8s'
    var imid = document.getElementById('imid')
    imid.style.transform = 'scale(1.1)'
    imid.style.transition = '0.8s'
    var idebut = document.getElementById('idebut')
    idebut.style.transform = 'scale(1.0)'
    var ispn = document.getElementById('ispn')
    ispn.style.transform = 'scale(1.0)'
    var ired = document.getElementById('ired')
    ired.style.transform = 'scale(1.0)'
    var inine = document.getElementById('inine')
    inine.style.transform = 'scale(1.0)'
    var irep = document.getElementById('irep')
    irep.style.transform = 'scale(1.0)'
    var ilover = document.getElementById('ilover')
    ilover.style.transform = 'scale(1.0)'
    var ifolk = document.getElementById('ifolk')
    ifolk.style.transform = 'scale(1.0)'
    var iever = document.getElementById('iever')
    iever.style.transform = 'scale(1.0)'
    var ifea = document.getElementById('ifea')
    ifea.style.transform = 'scale(1.0)'
    var ittpd = document.getElementById('ittpd')
    ittpd.style.transform = 'scale(1.0)'
}

function ttpd(){
    var t = document.getElementById('ttpd')
    t.style.width = '400px'
    t.style.transition = '0.8s'
    art.style.marginLeft = '8px'
    art.style.transition = '0.8s'

    var music = document.getElementById('music')
    music.style.background = '#cccccc'
    music.style.transition = '0.8s'

    var f = document.getElementById('fearless')
    f.style.width = '95.4px'
    f.style.transition = '0.8s'
    var s = document.getElementById('spn')
    s.style.width = '95.4px'
    s.style.transition = '0.8s'
    var r = document.getElementById('red')
    r.style.width = '95.4px'
    r.style.transition = '0.8s'
    var n = document.getElementById('nine')
    n.style.width = '95.4px'
    n.style.transition = '0.8s'
    var rp = document.getElementById('rep')
    rp.style.width = '95.4px'
    rp.style.transition = '0.8s'
    var l = document.getElementById('lover')
    l.style.width = '95.4px'
    l.style.transition = '0.8s'
    var fk = document.getElementById('folk')
    fk.style.width = '95.4px'
    fk.style.transition = '0.8s'
    var e = document.getElementById('ever')
    e.style.width = '95.4px'
    e.style.transition = '0.8s'
    var m = document.getElementById('mid')
    m.style.width = '95.4px'
    m.style.transition = '0.8s'
    var d = document.getElementById('debut')
    d.style.width = '95.4px'
    d.style.transition = '0.8s'
    var ittpd = document.getElementById('ittpd')
    ittpd.style.transform = 'scale(1.1)'
    ittpd.style.transition = '0.8s'
    var idebut = document.getElementById('idebut')
    idebut.style.transform = 'scale(1.0)'
    var ispn = document.getElementById('ispn')
    ispn.style.transform = 'scale(1.0)'
    var ired = document.getElementById('ired')
    ired.style.transform = 'scale(1.0)'
    var inine = document.getElementById('inine')
    inine.style.transform = 'scale(1.0)'
    var irep = document.getElementById('irep')
    irep.style.transform = 'scale(1.0)'
    var ilover = document.getElementById('ilover')
    ilover.style.transform = 'scale(1.0)'
    var ifolk = document.getElementById('ifolk')
    ifolk.style.transform = 'scale(1.0)'
    var iever = document.getElementById('iever')
    iever.style.transform = 'scale(1.0)'
    var imid = document.getElementById('imid')
    imid.style.transform = 'scale(1.0)'
    var ifea = document.getElementById('ifea')
    ifea.style.transform = 'scale(1.0)'
}